name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: dom, curl, libxml, mbstring, zip, sqlite3
        coverage: pcov

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Prepare Environment
      run: |
        cp .env.example .env
        php artisan key:generate

    - name: Run Tests
      run: php artisan test --coverage-clover=coverage.xml
